"""empty message

Revision ID: 0f57dde49bed
Revises: 
Create Date: 2023-08-21 20:58:54.086215

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f57dde49bed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bird_image_sound',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_by', sa.String(length=40), nullable=False, comment='提供者'),
    sa.Column('path', sa.String(length=100), nullable=False, comment='存储路径'),
    sa.Column('label', sa.String(length=40), nullable=False, comment='类型 图片或声音'),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('is_lock', sa.Boolean(), nullable=False, comment='是否删除该目录'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bird_inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_en', sa.String(length=40), nullable=False, comment='目英文'),
    sa.Column('order_cn', sa.String(length=40), nullable=False, comment='目中文'),
    sa.Column('family_en', sa.String(length=40), nullable=False, comment='科英文'),
    sa.Column('family_cn', sa.String(length=40), nullable=False, comment='科中文'),
    sa.Column('genus', sa.String(length=40), nullable=False, comment='属'),
    sa.Column('species', sa.String(length=40), nullable=False, comment='种'),
    sa.Column('latin_name', sa.String(length=40), nullable=False, comment='拉丁名'),
    sa.Column('geotype', sa.String(length=40), nullable=True, comment='地理型'),
    sa.Column('seasonal', sa.String(length=200), nullable=True, comment='季节型 逗号分割'),
    sa.Column('IUCN', sa.String(length=40), nullable=True, comment='濒危等级'),
    sa.Column('level', sa.String(length=100), nullable=True, comment='保护等级'),
    sa.Column('describe', sa.String(length=200), nullable=True, comment='描述'),
    sa.Column('habitat', sa.String(length=200), nullable=True, comment='生境'),
    sa.Column('behavior', sa.String(length=200), nullable=True, comment='习性'),
    sa.Column('bird_info', sa.String(length=200), nullable=True, comment='鸟类声音图像信息id 逗号隔开添加'),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('is_check', sa.Boolean(), nullable=False, comment='是否检查'),
    sa.Column('is_lock', sa.Boolean(), nullable=False, comment='是否删除该鸟'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bird_match',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_create', sa.String(length=200), nullable=False, comment='举办人/单位'),
    sa.Column('match_name', sa.String(length=60), nullable=False, comment='比赛名称'),
    sa.Column('match_desc', sa.String(length=200), nullable=True, comment='比赛描述'),
    sa.Column('match_location', sa.String(length=200), nullable=False, comment='比赛地点'),
    sa.Column('referee', sa.String(length=200), nullable=False, comment='裁判信息 逗号隔开添加'),
    sa.Column('match_image', sa.String(length=200), nullable=True, comment='比赛banner图片'),
    sa.Column('start_time', sa.DateTime(), nullable=False, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(), nullable=False, comment='结束时间'),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('is_lock', sa.Boolean(), nullable=False, comment='是否删除'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bird_survey',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='调查人id'),
    sa.Column('survey_name', sa.String(length=40), nullable=False, comment='调查名称'),
    sa.Column('survey_desc', sa.String(length=200), nullable=True, comment='调查描述'),
    sa.Column('survey_time', sa.DateTime(), nullable=False, comment='调查时间'),
    sa.Column('survey_location', sa.String(length=200), nullable=False, comment='调查地点'),
    sa.Column('describe', sa.String(length=200), nullable=False, comment='描述'),
    sa.Column('habitat', sa.String(length=200), nullable=False, comment='生境'),
    sa.Column('behavior', sa.String(length=200), nullable=False, comment='习性'),
    sa.Column('bird_info', sa.String(length=200), nullable=False, comment='鸟类声音图像信息,逗号分割'),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('is_check', sa.Boolean(), nullable=False, comment='是否检查'),
    sa.Column('is_lock', sa.Boolean(), nullable=False, comment='是否删除调查'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_session_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('openid', sa.String(length=255), nullable=True),
    sa.Column('session_key', sa.String(length=255), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logon_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('hash_password', sa.String(length=120), nullable=False, comment='密码'),
    sa.Column('phone', sa.String(length=20), nullable=False, comment='手机号'),
    sa.Column('email', sa.String(length=20), nullable=True, comment='邮箱'),
    sa.Column('avatar', sa.String(length=100), nullable=True, comment='头像'),
    sa.Column('role', sa.Enum('sysadmin', 'admin', 'others'), nullable=False, comment='权限sysadmin-超级管理员，admin-管理员，others-其他'),
    sa.Column('depart', sa.Integer(), nullable=False, comment='默认0--unowned'),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('login_date', sa.DateTime(), nullable=False, comment='最后登陆时间'),
    sa.Column('is_lock', sa.Boolean(), nullable=False, comment='是否删除该用户'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('userdata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('openid', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('province', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True, comment='积分'),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bird_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False, comment='比赛id'),
    sa.Column('group_name', sa.String(length=60), nullable=False, comment='小组名称'),
    sa.Column('hash_password', sa.String(length=120), nullable=False, comment='密码'),
    sa.Column('group_desc', sa.String(length=200), nullable=True, comment='小组描述'),
    sa.Column('group_user', sa.String(length=200), nullable=False, comment='小组成员 逗号隔开添加'),
    sa.Column('rank', sa.Integer(), nullable=True, comment='小组排名'),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('is_lock', sa.Boolean(), nullable=False, comment='是否结束小组'),
    sa.ForeignKeyConstraint(['match_id'], ['bird_match.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_name')
    )
    op.create_table('bird_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='记录用户id'),
    sa.Column('bird_id', sa.Integer(), nullable=False, comment='鸟类名录ID'),
    sa.Column('record_time', sa.DateTime(), nullable=False, comment='时间'),
    sa.Column('record_location', sa.String(length=200), nullable=False, comment='地点'),
    sa.Column('longitude', sa.Float(), nullable=False, comment='经度'),
    sa.Column('latitude', sa.Float(), nullable=False, comment='经度'),
    sa.Column('weather', sa.String(length=40), nullable=False, comment='天气'),
    sa.Column('temperature', sa.Float(), nullable=False, comment='气温'),
    sa.Column('record_describe', sa.String(length=200), nullable=True, comment='描述'),
    sa.Column('bird_info', mysql.LONGTEXT(), nullable=True, comment='鸟类声音图像信息 逗号隔开添加'),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('is_check', sa.Boolean(), nullable=False, comment='是否检查'),
    sa.Column('is_lock', sa.Boolean(), nullable=False, comment='是否删除该记录'),
    sa.ForeignKeyConstraint(['bird_id'], ['bird_inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bird_records')
    op.drop_table('bird_group')
    op.drop_table('userdata')
    op.drop_table('logon_user')
    op.drop_table('login_session_cache')
    op.drop_table('bird_survey')
    op.drop_table('bird_match')
    op.drop_table('bird_inventory')
    op.drop_table('bird_image_sound')
    # ### end Alembic commands ###
