"""empty message

Revision ID: 1a6e4ff326f2
Revises: 0f57dde49bed
Create Date: 2023-08-21 23:17:58.434884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a6e4ff326f2'
down_revision = '0f57dde49bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bird_records', schema=None) as batch_op:
        batch_op.drop_constraint('bird_records_ibfk_1', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bird_records', schema=None) as batch_op:
        batch_op.create_foreign_key('bird_records_ibfk_1', 'bird_inventory', ['bird_id'], ['id'])

    # ### end Alembic commands ###
