"""empty message

Revision ID: 23c8a68e6a52
Revises: e6fb69d7eb88
Create Date: 2023-08-23 23:42:56.298814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23c8a68e6a52'
down_revision = 'e6fb69d7eb88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('feedback_text', sa.String(length=500), nullable=False, comment='反馈内容'),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False, comment='是否已解决'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False, comment='通知标题'),
    sa.Column('content', sa.String(length=500), nullable=False, comment='通知内容'),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.Column('is_lock', sa.Boolean(), nullable=False, comment='结束通知'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_notifications')
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
