"""empty message

Revision ID: 2cd3306b7e79
Revises: 1f0ae20825ea
Create Date: 2023-11-04 10:18:04.211383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cd3306b7e79'
down_revision = '1f0ae20825ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userdata', schema=None) as batch_op:
        batch_op.add_column(sa.Column('limit', sa.Integer(), nullable=True, comment='权限'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userdata', schema=None) as batch_op:
        batch_op.drop_column('limit')

    # ### end Alembic commands ###
