"""Initial migration.

Revision ID: 99f2cfff3729
Revises: 
Create Date: 2023-07-09 13:28:48.197568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f2cfff3729'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_session_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openid', sa.String(length=255), nullable=True),
    sa.Column('session_key', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openid', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('province', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userdata')
    op.drop_table('login_session_cache')
    # ### end Alembic commands ###
